name: Release and Deploy to PyPI

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-22.04

    outputs:
      version: ${{ steps.read_version.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: "3.11"

      - name: Read Version from Tag
        id: read_version
        run: |
          # Extract the version from the tag name
          version="${GITHUB_REF#refs/tags/v}"
          echo "Tag version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ steps.read_version.outputs.version }}"
          gh release create "v$version" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} $version" \
            --generate-notes

  deploy:
    runs-on: ubuntu-22.04
    needs: release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: "3.11"

      - name: Configure Poetry Authentication
        env:
          POETRY_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi "$POETRY_TOKEN"

      - name: Build and Publish Package to PyPI
        run: |
          poetry build
          poetry publish
