name: Release and Deploy to PyPI on Version Change

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure the full repository history is fetched

      - name: Setup Python Environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: "3.11"
          poetry-version: "1.8.3"

      - name: Read Version from Current Branch
        id: current_version
        run: |
          version=$(grep -Po 'version\s*=\s*"\K[^"]+' pyproject.toml)
          echo "Current branch version: $version"
          echo "version=$version" >> $GITHUB_ENV
          echo "::set-output name=version::$version"

      - name: Fetch Main Branch into Detached HEAD
        run: |
          git fetch origin main:refs/remotes/origin/main
          git checkout origin/main

      - name: Read Version from Main Branch
        id: main_version
        run: |
          version=$(grep -Po 'version\s*=\s*"\K[^"]+' pyproject.toml)
          echo "Main branch version: $version"
          echo "version=$version" >> $GITHUB_ENV
          echo "::set-output name=version::$version"

      - name: Compare Versions
        id: compare_versions
        run: |
          if [ "${{ steps.current_version.outputs.version }}" = "${{ steps.main_version.outputs.version }}" ]; then
            echo "Version has not changed. Skipping release."
            exit 0
          else
            echo "Version has changed. Proceeding with release."
          fi

      - name: Checkout Current Branch
        run: |
          git checkout -

      - name: Create Version Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v${{ steps.current_version.outputs.version }}" -m "Release version v${{ steps.current_version.outputs.version }}"
          git push origin "v${{ steps.current_version.outputs.version }}"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v${{ steps.current_version.outputs.version }}
        run: |
          gh release create "$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${TAG#v}" \
              --generate-notes

      - name: Configure Poetry Authentication
        env:
          POETRY_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi "$POETRY_TOKEN"

      - name: Build and Publish Package to PyPI
        run: |
          poetry build
          poetry publish
