name: Pipeline

on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: 3.12.0
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root
      - name: Run ruff
        run: |
          poetry run pre-commit run -a 

  run-tests:
    needs: code-quality
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: 3.12.0
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root --extras all
      - name: Run tests
        run: |
          poetry run pytest tests/transcription/test_google_transcription.py --disable-warnings
